// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primtypes.djinni

pub struct AssortedPrimitives {
    pub b: bool,
    pub eight: i8,
    pub sixteen: i16,
    pub thirtytwo: i32,
    pub sixtyfour: i64,
    pub fthirtytwo: f32,
    pub fsixtyfour: f64,
    pub o_b: Option<bool>,
    pub o_eight: Option<i8>,
    pub o_sixteen: Option<i16>,
    pub o_thirtytwo: Option<i32>,
    pub o_sixtyfour: Option<i64>,
    pub o_fthirtytwo: Option<f32>,
    pub o_fsixtyfour: Option<f64>,
}
