// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

use generated_rust::client_returned_record::ClientReturnedRecord;
use mopa;

pub trait ClientInterface: mopa::Any {
    fn get_record(&self, record_id: i64, utf8string: String, misc: Option<String>) -> ClientReturnedRecord;
    fn return_str(&self) -> String;
}

mopafy!(ClientInterface);
