// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

pub trait ClientInterface {
    fn get_record(&self, record_id: i64, utf8string: String, misc: Option<String>) -> ::generated_rust::ClientReturnedRecord;
    fn identifier_check(&self, data: Box<[u8]>, r: i32, jret: i64) -> f64;
    fn return_str(&self) -> String;
}
