// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

pub trait ConstantsInterface {
    // non-static method dummy goes here

    // const BOOL_CONSTANT goes here
    // const I8_CONSTANT goes here
    // const I16_CONSTANT goes here
    // const I32_CONSTANT goes here
    // const I64_CONSTANT goes here
    // const F32_CONSTANT goes here
    // const F64_CONSTANT goes here
}
