// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from exception.djinni

use std::sync::Arc;
use std::boxed::Box;
use generated_rust::cpp_exception::CppException;
pub trait CppException {
    fn throw_an_exception(&self) -> i32;
    fn get() -> Arc<Box<CppException>>;
}
