// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from exception.djinni

use std::sync::Arc;
use std::boxed::Box;
use mopa;

pub trait CppException: mopa::Any {
    fn throw_an_exception(&self) -> i32;
}

mopafy!(CppException);
