// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from exception.djinni

pub trait CppException {
    fn throw_an_exception(&self) -> i32;
    // would be get, but DInterface not implemented
}
