// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from date.djinni

pub struct DateRecord {
    // would be created_at, but MExtern not implemented
    dummy: u8
}

// TODO(rustgen): deriving eq

// TODO(rustgen): deriving ord
