// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

pub struct ExternRecordWithDerivings {
    // would be member, but MExtern not implemented
    // would be e, but MExtern not implemented
}
