// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

use std::collections::HashMap;
pub struct MapRecord {
    pub map: HashMap<String, i64>,
    pub imap: HashMap<i32, i32>,
}
