// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nested_collection.djinni

use std::collections::HashSet;
pub struct NestedCollection {
    pub set_list: Vec<HashSet<String>>,
}
