// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from interface_nullity.djinni

pub trait NullityInterface {
    fn non_null_parameters(&self, p1: Arc<Box<::generated_rust::dummy_interface::DummyInterface>>, p2: Arc<Box<::generated_rust::dummy_interface::DummyInterface>>);
    fn non_null_return(&self, should_return_null: bool) -> Arc<Box<::generated_rust::dummy_interface::DummyInterface>>;
    fn nullable_parameters(&self, p1: Option<Arc<Box<::generated_rust::dummy_interface::DummyInterface>>>, p2: Option<Arc<Box<::generated_rust::dummy_interface::DummyInterface>>>);
    fn nullable_return(&self, should_return_null: bool) -> Option<Arc<Box<::generated_rust::dummy_interface::DummyInterface>>>;
}
