// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from derivings.djinni

pub struct RecordWithNestedDerivings {
    pub key: i32,
    pub rec: RecordWithDerivings,
}

// TODO(rustgen): deriving eq

// TODO(rustgen): deriving ord
