// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from derivings.djinni

use generated_rust::record_with_derivings::RecordWithDerivings;
pub struct RecordWithNestedDerivings {
    pub key: i32,
    pub rec: RecordWithDerivings,
}

// TODO(rustgen): deriving eq

// TODO(rustgen): deriving ord
