// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from derivings.djinni

pub struct RecordWithDerivings {
    pub key1: i32,
    pub key2: String,
}

// TODO(rustgen): deriving eq

// TODO(rustgen): deriving ord
