// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from duration.djinni

pub struct RecordWithDurationAndDerivings {
    // would be dt, but MExtern not implemented
}

// TODO(rustgen): deriving eq

// TODO(rustgen): deriving ord
