// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from set.djinni

use std::collections::HashSet;
pub struct SetRecord {
    pub set: HashSet<String>,
    pub iset: HashSet<i32>,
}
