// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from interface_nullity.djinni

use std::sync::Arc;
use std::boxed::Box;
use generated_rust::dummy_interface::DummyInterface;
use mopa;

pub trait StaticNullityInterface: mopa::Any {
}

mopafy!(StaticNullityInterface);
