// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from duration.djinni

pub trait TestDuration {
    // would be hoursString, but MExtern not implemented
    // would be minutesString, but MExtern not implemented
    // would be secondsString, but MExtern not implemented
    // would be millisString, but MExtern not implemented
    // would be microsString, but MExtern not implemented
    // would be nanosString, but MExtern not implemented
    // would be hours, but MExtern not implemented
    // would be minutes, but MExtern not implemented
    // would be seconds, but MExtern not implemented
    // would be millis, but MExtern not implemented
    // would be micros, but MExtern not implemented
    // would be nanos, but MExtern not implemented
    // would be hoursf, but MExtern not implemented
    // would be minutesf, but MExtern not implemented
    // would be secondsf, but MExtern not implemented
    // would be millisf, but MExtern not implemented
    // would be microsf, but MExtern not implemented
    // would be nanosf, but MExtern not implemented
    // would be box, but MExtern not implemented
    // would be unbox, but MExtern not implemented
}
