// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

pub trait TestHelpers {
    fn get_set_record() -> SetRecord;
    fn check_set_record(rec: SetRecord) -> bool;
    fn get_primitive_list() -> PrimitiveList;
    fn check_primitive_list(pl: PrimitiveList) -> bool;
    fn get_nested_collection() -> NestedCollection;
    fn check_nested_collection(nc: NestedCollection) -> bool;
    fn get_map() -> HashMap<String, i64>;
    fn check_map(m: HashMap<String, i64>) -> bool;
    fn get_empty_map() -> HashMap<String, i64>;
    fn check_empty_map(m: HashMap<String, i64>) -> bool;
    fn get_map_list_record() -> MapListRecord;
    fn check_map_list_record(m: MapListRecord) -> bool;
    fn check_client_interface_ascii(i: Arc<Box<ClientInterface>>);
    fn check_client_interface_nonascii(i: Arc<Box<ClientInterface>>);
    fn check_enum_map(m: HashMap<Color, String>);
    fn check_enum(c: Color);
    fn token_id(t: Option<Arc<Box<UserToken>>>) -> Option<Arc<Box<UserToken>>>;
    fn create_cpp_token() -> Arc<Box<UserToken>>;
    fn check_cpp_token(t: Arc<Box<UserToken>>);
    fn cpp_token_id(t: Arc<Box<UserToken>>) -> i64;
    fn check_token_type(t: Arc<Box<UserToken>>, expected_type: String) -> bool;
    fn return_none() -> Option<i32>;
    fn assorted_primitives_id(i: AssortedPrimitives) -> AssortedPrimitives;
    fn id_binary(b: Box<[u8]>) -> Box<[u8]>;
    fn get_nullity_interface() -> Arc<Box<NullityInterface>>;
    fn check_interface_nullity_parameters(i: Arc<Box<NullityInterface>>);
    fn check_interface_nullity_return(i: Arc<Box<NullityInterface>>);
}
