// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

pub trait TestHelpers {
    fn get_set_record() -> SetRecord;
    fn check_set_record(rec: SetRecord) -> bool;
    fn get_primitive_list() -> PrimitiveList;
    fn check_primitive_list(pl: PrimitiveList) -> bool;
    fn get_nested_collection() -> NestedCollection;
    fn check_nested_collection(nc: NestedCollection) -> bool;
    fn get_map() -> HashMap<String, i64>;
    fn check_map(m: HashMap<String, i64>) -> bool;
    fn get_empty_map() -> HashMap<String, i64>;
    fn check_empty_map(m: HashMap<String, i64>) -> bool;
    fn get_map_list_record() -> MapListRecord;
    fn check_map_list_record(m: MapListRecord) -> bool;
    // would be check_client_interface_ascii, but DInterface not implemented
    // would be check_client_interface_nonascii, but DInterface not implemented
    fn check_enum_map(m: HashMap<Color, String>);
    fn check_enum(c: Color);
    // would be token_id, but DInterface not implemented
    // would be create_cpp_token, but DInterface not implemented
    // would be check_cpp_token, but DInterface not implemented
    // would be cpp_token_id, but DInterface not implemented
    // would be check_token_type, but DInterface not implemented
    fn return_none() -> Option<i32>;
    fn assorted_primitives_id(i: AssortedPrimitives) -> AssortedPrimitives;
    fn id_binary(b: Box<[u8]>) -> Box<[u8]>;
    // would be get_nullity_interface, but DInterface not implemented
    // would be check_interface_nullity_parameters, but DInterface not implemented
    // would be check_interface_nullity_return, but DInterface not implemented
}
