// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

pub trait TestHelpers {
    fn get_set_record() -> ::generated_rust::SetRecord;
    fn check_set_record(rec: ::generated_rust::SetRecord) -> bool;
    fn get_primitive_list() -> ::generated_rust::PrimitiveList;
    fn check_primitive_list(pl: ::generated_rust::PrimitiveList) -> bool;
    fn get_nested_collection() -> ::generated_rust::NestedCollection;
    fn check_nested_collection(nc: ::generated_rust::NestedCollection) -> bool;
    fn get_map() -> HashMap<String, i64>;
    fn check_map(m: HashMap<String, i64>) -> bool;
    fn get_empty_map() -> HashMap<String, i64>;
    fn check_empty_map(m: HashMap<String, i64>) -> bool;
    fn get_map_list_record() -> ::generated_rust::MapListRecord;
    fn check_map_list_record(m: ::generated_rust::MapListRecord) -> bool;
    fn check_client_interface_ascii(i: Arc<Box<::generated_rust::ClientInterface>>);
    fn check_client_interface_nonascii(i: Arc<Box<::generated_rust::ClientInterface>>);
    fn check_enum_map(m: HashMap<::generated_rust::Color, String>);
    fn check_enum(c: ::generated_rust::Color);
    fn token_id(t: Option<Arc<Box<::generated_rust::UserToken>>>) -> Option<Arc<Box<::generated_rust::UserToken>>>;
    fn create_cpp_token() -> Arc<Box<::generated_rust::UserToken>>;
    fn check_cpp_token(t: Arc<Box<::generated_rust::UserToken>>);
    fn cpp_token_id(t: Arc<Box<::generated_rust::UserToken>>) -> i64;
    fn check_token_type(t: Arc<Box<::generated_rust::UserToken>>, expected_type: String) -> bool;
    fn return_none() -> Option<i32>;
    fn assorted_primitives_id(i: ::generated_rust::AssortedPrimitives) -> ::generated_rust::AssortedPrimitives;
    fn id_binary(b: Box<[u8]>) -> Box<[u8]>;
    fn get_nullity_interface() -> Arc<Box<::generated_rust::NullityInterface>>;
    fn check_interface_nullity_parameters(i: Arc<Box<::generated_rust::NullityInterface>>);
    fn check_interface_nullity_return(i: Arc<Box<::generated_rust::NullityInterface>>);
}
