// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#[macro_use]
use support_lib;
use support_lib::support::JType;
use support_lib::jni_ffi::{JNIEnv, jobject};
use generated_rust::client_returned_record::ClientReturnedRecord;

pub struct NativeClientReturnedRecord;
impl JType for NativeClientReturnedRecord
{
    type RustType = ClientReturnedRecord;
    type JniType = jobject;

    #[allow(non_snake_case)]
    fn to_rust(jni_env: *mut JNIEnv, j: Self::JniType) -> Self::RustType {
        // TODO(rustgen): have a local scope here
        // TODO(rustgen): use a helper to get the class/methods so they're cached
        let class = support_lib::support::get_class(jni_env, "com/dropbox/djinni/test/ClientReturnedRecord");
        let field_mRecordId = support_lib::support::get_method(jni_env, class, "mRecordId", "J");
        let field_mContent = support_lib::support::get_method(jni_env, class, "mContent", "Ljava/lang/String;");
        let field_mMisc = support_lib::support::get_method(jni_env, class, "mMisc", "Ljava/lang/String;");

        assert!(j != 0 as jobject);
        ClientReturnedRecord {
            record_id: support_lib::support::I64::to_rust(jni_env, jni_invoke!(jni_env, GetLongField, j, field_mRecordId)),
            content: support_lib::support::String::to_rust(jni_env, (jstring)jni_invoke!(jni_env, GetObjectField, j, field_mContent)),
            misc: support_lib::support::Optional::<support_lib::support::String>::to_rust(jni_env, (jstring)jni_invoke!(jni_env, GetObjectField, j, field_mMisc)),
        }
    }

    fn from_rust(jni_env: *mut JNIEnv, r: Self::RustType) -> Self::JniType {
        // TODO(rustgen): translate backwards
        0 as jobject
    }

    fn to_rust_boxed(jni_env: *mut JNIEnv, j: jobject) -> Self::RustType {
        Self::to_rust(jni_env, j)
    }

    fn from_rust_boxed(jni_env: *mut JNIEnv, r: Self::RustType) -> jobject {
        Self::from_rust(jni_env, r)
    }
}
