// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from interface_nullity.djinni

use support_lib::support::jni_get_thread_env;
use support_lib::support::get_class;
use support_lib::support::get_field;
use support_lib::jni_ffi::jobject;
use generated_rust_jni;
use support_lib::support::ForVariadic;
use generated_rust::dummy_interface::DummyInterface;
use std::sync::Arc;
use std::boxed::Box;
use support_lib::support::RustProxyable;
use support_lib::support::JType;
use support_lib::support::get_method;
use support_lib::jni_ffi::JNIEnv;
use support_lib::support::GlobalRef;
use support_lib::jni_ffi::jclass;
use support_lib::jni_ffi::jlong;
use std::mem;

// TODO(rustgen): correct strong/weak Java references
// TODO(rustgen): cache the proxies
// TODO(rustgen): look into using catch_panic
impl JType for Arc<Box<DummyInterface>> {
    type JniType = jobject;

    fn to_rust(jni_env: *mut JNIEnv, j: Self::JniType) -> Self {
        let proxy_class = get_class(jni_env, "com/dropbox/djinni/test/DummyInterface$CppProxy");
        let object_class = jni_invoke!(jni_env, GetObjectClass, j);
        let is_proxy = bool::to_rust(jni_env, jni_invoke!(jni_env, IsSameObject, proxy_class, object_class));
        if is_proxy {
            assert!(is_proxy);
            let native_ref_field = get_field(jni_env, proxy_class, "nativeRef", "J");
            let handle = jni_invoke!(jni_env, GetLongField, j, native_ref_field);
            *Self::from_handle(handle)
        } else {
            Arc::new(Box::new(DummyInterfaceJavaProxy { java_ref: GlobalRef::new(jni_env, j) }))
        }
    }

    fn from_rust(jni_env: *mut JNIEnv, r: Self) -> Self::JniType {
        if let Some(proxy) = r.downcast_ref::<DummyInterfaceJavaProxy>() {
            return proxy.java_ref.get();
        }
        // Is not a Java proxy, need to create a new CppProxy
        // TODO(rustgen) - cache the CppProxys
        let class = ::support_lib::support::get_class(jni_env, "com/dropbox/djinni/test/DummyInterface$CppProxy");
        let constructor = ::support_lib::support::get_method(jni_env, class, "<init>", "(J)V");
        let handle = Self::to_handle(r.clone());
        jni_invoke!(jni_env, NewObject, class, constructor, handle)
    }

    fn to_rust_boxed(jni_env: *mut JNIEnv, j: jobject) -> Self {
        Self::to_rust(jni_env, j)
    }

    fn from_rust_boxed(jni_env: *mut JNIEnv, r: Self) -> jobject {
        Self::from_rust(jni_env, r)
    }
}

impl RustProxyable for Arc<Box<DummyInterface>> {
    fn to_handle(self) -> jlong {
        // Convert our box into a pointer, leaving the memory there and not running
        // the destructor on the contents. We can't use Box::into_raw since it's unstable.
        unsafe { mem::transmute(Box::new(self)) }
    }
    fn from_handle(rust_proxy_handle: jlong) -> Box<Self> {
        // Convert our pointer back into a box. We can't use Box::from_raw since it's unstable.
        unsafe { mem::transmute(rust_proxy_handle as *mut Arc<Box<Self>>) }
    }
}

struct DummyInterfaceJavaProxy {
    java_ref: GlobalRef
}

impl DummyInterface for DummyInterfaceJavaProxy {
}

struct DummyInterfaceCppProxy {
    rust_ref: Arc<Box<DummyInterface>>
}

#[no_mangle]
#[inline(never)]
#[allow(non_snake_case)]
pub extern "C" fn Java_com_dropbox_djinni_test_DummyInterface_00024CppProxy_nativeDestroy(jni_env: *mut JNIEnv, _this: jobject, native_ref: jlong) {
    let _to_delete: Box<Arc<Box<DummyInterface>>> = Arc::<Box<DummyInterface>>::from_handle(native_ref);
    // Let the destructor run on the Box and its Arc when _to_delete goes out of scope.
}
