// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#[macro_use(jni_invoke)]
use support_lib;
use support_lib::support::{JType, ForVaridaic};
use support_lib::jni_ffi::{JNIEnv, jobject};
use generated_rust::extern_record_with_derivings::ExternRecordWithDerivings;

pub struct NativeExternRecordWithDerivings;
impl JType for NativeExternRecordWithDerivings
{
    type RustType = ExternRecordWithDerivings;
    type JniType = jobject;

    fn to_rust(jni_env: *mut JNIEnv, j: Self::JniType) -> Self::RustType {
        // TODO(rustgen): have a local scope here
        // TODO(rustgen): use a helper to get the class/methods so they're cached
        let class = support_lib::support::get_class(jni_env, "com/dropbox/djinni/test/ExternRecordWithDerivings");
        let field_member = support_lib::support::get_method(jni_env, class, "mMember", "Lcom/dropbox/djinni/test/RecordWithDerivings;");
        let field_e = support_lib::support::get_method(jni_env, class, "mE", "Lcom/dropbox/djinni/test/Color;");

        assert!(j != 0 as jobject);
        ExternRecordWithDerivings {
            // would grab field_member, but MExtern not implemented
            // would grab field_e, but MExtern not implemented
        }
    }

    fn from_rust(jni_env: *mut JNIEnv, r: Self::RustType) -> Self::JniType {
        // TODO(rustgen): cache the class/methods
        // TODO(rustgen): class object should have a ref around it
        let class = support_lib::support::get_class(jni_env, "com/dropbox/djinni/test/ExternRecordWithDerivings");
        let jconstructor = support_lib::support::get_method(jni_env, class, "<init>", "(Lcom/dropbox/djinni/test/RecordWithDerivings;Lcom/dropbox/djinni/test/Color;)V");

        // TODO(rustgen): handle local refs correctly
        jni_invoke!(jni_env, NewLocalRef, jni_invoke!(jni_env, NewObject, class, jconstructor,
                                                      // would grab member, but MExtern not implemented,
                                                      // would grab e, but MExtern not implemented))
    }

    fn to_rust_boxed(jni_env: *mut JNIEnv, j: jobject) -> Self::RustType {
        Self::to_rust(jni_env, j)
    }

    fn from_rust_boxed(jni_env: *mut JNIEnv, r: Self::RustType) -> jobject {
        Self::from_rust(jni_env, r)
    }
}
