// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from derivings.djinni

#[macro_use]
use support_lib;
use support_lib::support::JType;
use support_lib::jni_ffi::{JNIEnv, jobject};
use generated_rust::record_with_nested_derivings::RecordWithNestedDerivings;

pub struct NativeRecordWithNestedDerivings;
impl JType for NativeRecordWithNestedDerivings
{
    type RustType = RecordWithNestedDerivings;
    type JniType = jobject;

    #[allow(non_snake_case)]
    fn to_rust(jni_env: *mut JNIEnv, j: Self::JniType) -> Self::RustType {
        // TODO(rustgen): have a local scope here
        // TODO(rustgen): use a helper to get the class/methods so they're cached
        let class = support_lib::support::get_class(jni_env, "com/dropbox/djinni/test/RecordWithNestedDerivings");
        let field_mKey = support_lib::support::get_method(jni_env, class, "mKey", "I");
        let field_mRec = support_lib::support::get_method(jni_env, class, "mRec", "Lcom/dropbox/djinni/test/RecordWithDerivings;");

        assert!(j != 0 as jobject);
        RecordWithNestedDerivings {
            key: support_lib::support::I32::to_rust(jni_env, jni_invoke!(jni_env, GetIntField, j, field_mKey)),
            // would grab field_mRec, but MDef not implemented
        }
    }

    fn from_rust(jni_env: *mut JNIEnv, r: Self::RustType) -> Self::JniType {
        // TODO(rustgen): translate backwards
        0 as jobject
    }

    fn to_rust_boxed(jni_env: *mut JNIEnv, j: jobject) -> Self::RustType {
        Self::to_rust(jni_env, j)
    }

    fn from_rust_boxed(jni_env: *mut JNIEnv, r: Self::RustType) -> jobject {
        Self::from_rust(jni_env, r)
    }
}
