// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primtypes.djinni

pub struct AssortedPrimitives {
    pub b: bool,
    pub eight: i8,
    pub sixteen: i16,
    pub thirtytwo: i32,
    pub sixtyfour: i64,
    pub fthirtytwo: f32,
    pub fsixtyfour: f64,
    pub o_b: Optional<bool>,
    pub o_eight: Optional<i8>,
    pub o_sixteen: Optional<i16>,
    pub o_thirtytwo: Optional<i32>,
    pub o_sixtyfour: Optional<i64>,
    pub o_fthirtytwo: Optional<f32>,
    pub o_fsixtyfour: Optional<f64>,
}
