// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

pub trait ClientInterface {
    // non-static method get_record goes here
    // non-static method identifier_check goes here
    // non-static method return_str goes here
}
