// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

pub struct ClientReturnedRecord {
    pub record_id: i64,
    pub content: String,
    pub misc: Optional<String>,
}
