// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

pub trait ClientInterface {
    // would be get_record, but MDef not implemented
    // non-static method identifier_check goes here
    // non-static method return_str goes here
}
