// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

pub struct MapRecord {
    // would be map, but MMap not implemented
    // would be imap, but MMap not implemented
}
