// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from interface_nullity.djinni

pub trait NullityInterface {
    // would be non_null_parameters, but MDef not implemented
    // would be non_null_return, but MDef not implemented
    // would be nullable_parameters, but MDef not implemented
    // would be nullable_return, but MDef not implemented
}
