// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from derivings.djinni

pub struct RecordWithNestedDerivings {
    pub key: i32,
    // would be rec, but MDef not implemented
}
