// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from set.djinni

pub struct SetRecord {
    // would be set, but MSet not implemented
    // would be iset, but MSet not implemented
}
