// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from interface_nullity.djinni

pub trait StaticNullityInterface {
    // would be non_null_parameters, but DInterface not implemented
    // would be non_null_return, but DInterface not implemented
    // would be nullable_parameters, but DInterface not implemented
    // would be nullable_return, but DInterface not implemented
}
