// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

pub trait TestHelpers {
    // would be get_set_record, but MDef not implemented
    // would be check_set_record, but MDef not implemented
    // would be get_primitive_list, but MDef not implemented
    // would be check_primitive_list, but MDef not implemented
    // would be get_nested_collection, but MDef not implemented
    // would be check_nested_collection, but MDef not implemented
    // would be get_map, but MMap not implemented
    // would be check_map, but MMap not implemented
    // would be get_empty_map, but MMap not implemented
    // would be check_empty_map, but MMap not implemented
    // would be get_map_list_record, but MDef not implemented
    // would be check_map_list_record, but MDef not implemented
    // would be check_client_interface_ascii, but MDef not implemented
    // would be check_client_interface_nonascii, but MDef not implemented
    // would be check_enum_map, but MMap not implemented
    // would be check_enum, but MDef not implemented
    // would be token_id, but MDef not implemented
    // would be create_cpp_token, but MDef not implemented
    // would be check_cpp_token, but MDef not implemented
    // would be cpp_token_id, but MDef not implemented
    // would be check_token_type, but MDef not implemented
    fn return_none() -> Optional<i32>;
    // would be assorted_primitives_id, but MDef not implemented
    fn id_binary(b: Box<[u8]>) -> Box<[u8]>;
    // would be get_nullity_interface, but MDef not implemented
    // would be check_interface_nullity_parameters, but MDef not implemented
    // would be check_interface_nullity_return, but MDef not implemented
}
