// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#import "DBClientReturnedRecord.h"
#import <Foundation/Foundation.h>
@protocol DBClientInterface;


/** Client interface */
@protocol DBClientInterface

/** Returns record of given string */
- (nonnull DBClientReturnedRecord *)getRecord:(int64_t)recordId
                                   utf8string:(nonnull NSString *)utf8string
                                         misc:(nullable NSString *)misc;

/** identifier_check(data: binary, r: i32, jret: i64): f64; */
- (nonnull NSString *)returnStr;

- (nonnull NSString *)methTakingInterface:(nullable id<DBClientInterface>)i;

- (nonnull NSString *)methTakingOptionalInterface:(nullable id<DBClientInterface>)i;

@end
